#!/bin/sh

if [ -z $1 ] 
then
	exit
fi

# You can't target a tmux pane that has a period in the name
panename=$(echo "$1" | tr '.' '_' | grep -o '[^\/]*$')

session=$(tmux run-shell 'echo #S')
tmux new-window -n "$panename" "vim $1; tmux kill-pane -a"
# use this to get new pane id
# bash_var=$(tmux split-window -P -F "#{pane_id}") 
tmux split-window -t "$panename" -v -l 6 "TMUX= ;
	tmux -L tide-nest attach-session -t tide-$session-sh"
tmux select-pane -U
tmux split-window -t "$panename" -h -l 30 "TMUX= ;
	tmux -L tide-nest attach-session -t tide-$session-lf"
tmux select-pane -L
