#!/bin/sh

if [ -z $1 ]
then
	echo 'No project dir given'
	exit
fi

PROJDIR=$(cd $1; pwd)
cd $PROJDIR
PROJLASTPART=$(echo "$PROJDIR" | grep -o '[^\/]*$')

# test if a dir name containing a period will cause issues
tmux -L tmux-tide-$PROJLASTPART -f ~/.config/tmux/tidetmux.conf new-session -d
tmux -L tmux-tide-$PROJLASTPART -f ~/.config/tmux/tidetmux.conf new-session -d -s $PROJLASTPART 'lf -config ~/.config/lf/tidelfrc'
abduco -n tide-$PROJLASTPART-sh bash
abduco -n tide-$PROJLASTPART-lf lf -config ~/.config/lf/tidelfrc
exec st -e tmux -L tmux-tide-$PROJLASTPART attach-session -t $PROJLASTPART
