#!/bin/sh

if [ -z $1 ] 
then
	exit
fi

# You can't target a tmux pane that has a period in the name
panename=$(echo "$1" | tr '.' '_' | grep -o '[^\/]*$')

session=$(tmux run-shell 'echo #S')
tmux new-window -n "$panename" "vim $1; tmux kill-pane -a"
tmux split-window -t "$panename" -v -l 6 "abduco -a tide-$session-sh"
tmux select-pane -U
tmux split-window -t "$panename" -h -l 30 "abduco -a tide-$session-lf"
tmux select-pane -L
